name = "prd-vspo-portal-cron"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/cron/index.ts"
# tail_consumers = [{service = "prd-vspo-portal-cron-tail"}]
logpush = true
[dev]
port = 3002

[[services]]
binding = "APP_WORKER"
service = "prd-vspo-portal-app"
entrypoint = "ApplicationService"

[triggers]
crons = [ "0 0,7,18 * * *", "5 0,7,18 * * *", "*/2 * * * *", "*/30 * * * *", "*/2 * * * *" ]

[[workflows]]
name = "prd-search-videos-workflow"
binding = "SEARCH_VIDEOS_WORKFLOW"
class_name = "SearchVideosWorkflow"

[[workflows]]
name = "prd-search-channels-workflow"
binding = "SEARCH_CHANNELS_WORKFLOW"
class_name = "SearchChannelsWorkflow"

[[workflows]]
name = "prd-translate-videos-workflow"
binding = "TRANSLATE_VIDEOS_WORKFLOW"
class_name = "TranslateVideosWorkflow"

[[workflows]]
name = "prd-translate-creators-workflow"
binding = "TRANSLATE_CREATORS_WORKFLOW"
class_name = "TranslateCreatorsWorkflow"

[[workflows]]
name = "prd-discord-send-messages-workflow"
binding = "DISCORD_SEND_MESSAGES_WORKFLOW"
class_name = "DiscordSendMessagesWorkflow"

[[workflows]]
name = "prd-search-member-videos-by-channel-workflow"
binding = "SEARCH_MEMBER_VIDEOS_BY_CHANNEL_WORKFLOW"
class_name = "SearchMemberVideosByChannelWorkflow"

[[workflows]]
name = "prd-delete-videos-workflow"
binding = "DELETE_VIDEOS_WORKFLOW"
class_name = "DeleteVideosWorkflow"

[[workflows]]
name = "prd-discord-delete-all-workflow"
binding = "DISCORD_DELETE_ALL_WORKFLOW"
class_name = "DiscordDeleteAllWorkflow"

[[workflows]]
name = "prd-discord-send-message-all-channel-workflow"
binding = "DISCORD_SEND_MESSAGE_ALL_CHANNEL_WORKFLOW"
class_name = "DiscordSendMessageAllChannelWorkflow"

[[workflows]]
name = "prd-discord-send-message-channels-workflow"
binding = "DISCORD_SEND_MESSAGE_CHANNELS_WORKFLOW"
class_name = "DiscordSendMessageChannelsWorkflow"

[vars]
SERVICE_NAME = "prd-vspo-portal-cron"
ENVIRONMENT = "production"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
