name = "prd-vspo-portal-cron"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/cron/index.ts"
# tail_consumers = [{service = "prd-vspo-portal-cron-tail"}]
logpush = true
[dev]
port = 3002

[[services]]
binding = "APP_WORKER"
service = "prd-vspo-portal-app"
entrypoint = "ApplicationService"

[triggers]
crons = [ "0 0,7,18 * * *", "5 0,7,18 * * *", "*/2 * * * *", "*/30 * * * *", "*/1 * * * *", "15 * * * *", "30 21 * * *" ]

[[workflows]]
name = "prd-search-streams-workflow"
binding = "SEARCH_STREAMS_WORKFLOW"
class_name = "SearchStreamsWorkflow"

[[workflows]]
name = "prd-search-channels-workflow"
binding = "SEARCH_CHANNELS_WORKFLOW"
class_name = "SearchChannelsWorkflow"

[[workflows]]
name = "prd-translate-streams-workflow"
binding = "TRANSLATE_STREAMS_WORKFLOW"
class_name = "TranslateStreamsWorkflow"

[[workflows]]
name = "prd-translate-creators-workflow"
binding = "TRANSLATE_CREATORS_WORKFLOW"
class_name = "TranslateCreatorsWorkflow"

[[workflows]]
name = "prd-discord-send-messages-workflow"
binding = "DISCORD_SEND_MESSAGES_WORKFLOW"
class_name = "DiscordSendMessagesWorkflow"

[[workflows]]
name = "prd-search-member-streams-by-channel-workflow"
binding = "SEARCH_MEMBER_STREAMS_BY_CHANNEL_WORKFLOW"
class_name = "SearchMemberStreamsByChannelWorkflow"

[[workflows]]
name = "prd-delete-streams-workflow"
binding = "DELETE_STREAMS_WORKFLOW"
class_name = "DeleteStreamsWorkflow"

[[workflows]]
name = "prd-discord-delete-all-workflow"
binding = "DISCORD_DELETE_ALL_WORKFLOW"
class_name = "DiscordDeleteAllWorkflow"

[[workflows]]
name = "prd-discord-send-message-all-channel-workflow"
binding = "DISCORD_SEND_MESSAGE_ALL_CHANNEL_WORKFLOW"
class_name = "DiscordSendMessageAllChannelWorkflow"

[[workflows]]
name = "prd-discord-send-message-channels-workflow"
binding = "DISCORD_SEND_MESSAGE_CHANNELS_WORKFLOW"
class_name = "DiscordSendMessageChannelsWorkflow"

[[workflows]]
name = "prd-exist-clips-workflow"
binding = "EXIST_CLIPS_WORKFLOW"
class_name = "ExistClipsWorkflow"

[[workflows]]
name = "prd-search-clips-workflow"
binding = "SEARCH_CLIPS_WORKFLOW"
class_name = "SearchClipsWorkflow"

[[workflows]]
name = "prd-search-clips-by-vspo-member-name-workflow"
binding = "SEARCH_CLIPS_BY_VSPO_MEMBER_NAME_WORKFLOW"
class_name = "SearchClipsByVspoMemberNameWorkflow"

[[workflows]]
name = "prd-access-vspo-schedule-site-workflow"
binding = "ACCESS_VSPO_SCHEDULE_SITE_WORKFLOW"
class_name = "AccessVspoScheduleSiteWorkflow"

[vars]
SERVICE_NAME = "prd-vspo-portal-cron"
ENVIRONMENT = "production"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
