name = "dev-vspo-portal-app"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/server/internal/application/index.ts"
# tail_consumers = [{service = "dev-vspo-portal-app-tail"}]
logpush = true
kv_namespaces = [
  { binding = "APP_KV", id = "0b6b968c69fc406c8d55aaf2cd657c2b" }
]

[dev]
port = 3001

[[hyperdrive]]
binding = "DB"
id = "4d99e5c5c0944294977331b93146876c"
localConnectionString = "postgres://user:password@localhost:5432/vspo"

[[queues.producers]]
 queue = "dev-write-queue"
 binding = "WRITE_QUEUE"

[[queues.consumers]]
 queue = "dev-write-queue"
 max_batch_size = 100
 max_batch_timeout = 3
 dead_letter_queue = "dev-write-queue-dead-letter"

[vars]
SERVICE_NAME = "dev-vspo-portal-app"
ENVIRONMENT = "development"
LOG_TYPE = "json"
LOG_MINLEVEL = "0"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
