name = "dev-vspo-portal-gateway"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/server/gateway.ts"
# tail_consumers = [{ service = "dev-vspo-portal-gateway-tail" }]
logpush = true
kv_namespaces = [
  { binding = "APP_KV", id = "0b6b968c69fc406c8d55aaf2cd657c2b" }
]

[dev]
port = 3000

[[services]]
binding = "APP_WORKER"
service = "dev-vspo-portal-app"
entrypoint = "ApplicationService"

[vars]
SERVICE_NAME = "dev-vspo-portal-gateway"
ENVIRONMENT = "development"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
