name = "prd-vspo-portal-app"
compatibility_date = "2024-10-22"
send_metrics = false
compatibility_flags = ["nodejs_compat", "nodejs_als"]
main = "cmd/server/internal/application/index.ts"
# tail_consumers = [{service = "prd-vspo-portal-app-tail"}]
logpush = true
kv_namespaces = [
  { binding = "APP_KV", id = "14bf3d407655490e9f377efbb4c3352b" }
]

[dev]
port = 3001

[[hyperdrive]]
binding = "DB"
id = "3dcd12f5b90f40f492ba5e1e24c2d210"
localConnectionString = "postgres://user:password@localhost:5432/vspo"

[[queues.producers]]
 queue = "prd-write-queue"
 binding = "WRITE_QUEUE"

[[queues.consumers]]
 queue = "prd-write-queue"
 max_batch_size = 100
 max_batch_timeout = 5
 dead_letter_queue = "prd-write-queue-dead-letter"

[vars]
SERVICE_NAME = "prd-vspo-portal-app"
ENVIRONMENT = "production"
LOG_TYPE = "json"
LOG_MINLEVEL = "1"
LOG_HIDE_POSITION = "true"

[observability]
enabled = true
